# Generated by Django 5.1.1 on 2025-01-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='original_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='processed_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
