# Generated by Django 5.1.1 on 2025-01-27 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_userimage_fake_prediction_userimage_real_prediction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProcessingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preprocessed_images', models.TextField()),
                ('faces_cropped_images', models.TextField()),
                ('heatmap_images', models.TextField()),
                ('original_video', models.CharField(max_length=255)),
                ('models_location', models.CharField(max_length=255)),
                ('output', models.TextField()),
                ('confidence', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
